import '../blocks/map/images/icon-1.png';
import '../blocks/map/images/icon-2.png';
import '../blocks/profile/images/facebook.png';
import '../blocks/profile/images/facebook-white.png';
import '../blocks/profile/images/twitter.png';
import '../blocks/profile/images/twitter-white.png';
import '../blocks/profile/images/dribbble.png';
import '../blocks/profile/images/dribbble-white.png';
import '../blocks/selectmenu/images/arrow-down.png';
import '../images/favicon.ico';
require('./main-header/main-header.js');